CXX = gcc
CFLAGS = -Wall

.PHONY : clean

all: countdown.c
	@echo "all"
	gcc countdown.c -o countdown
countdown: countdown.c
	@echo "countdown"
	gcc countdown.c -o countdown
clean :
	-rm edit $(objects)



